#!/bin/sh

if which podman>/dev/null; 
then 
PROGRAM=podman; 
else 
PROGRAM=docker; 
fi

$PROGRAM run -it --rm -v $PWD:/project docker.io/library/rust:1-bullseye sh -c \
    "rustup target add x86_64-pc-windows-gnu && \
    apt-get -y update && \
    apt-get -y install mingw-w64 && \
    cargo build --manifest-path /project/Cargo.toml --release --target x86_64-pc-windows-gnu"
